--조건에 맞는 사원 정보 조회하기

WITH RankedEmployees AS (
    SELECT EMP_NO, SUM(SCORE) SCORE, MAX(SUM(SCORE)) OVER () MaxScore
    FROM HR_GRADE
    GROUP BY EMP_NO
)

SELECT SCORE, EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES
JOIN RankedEmployees r USING(EMP_NO)
WHERE SCORE = r.MaxScore
ORDER BY SCORE DESC;